# referer: https://github.com/marketplace/actions/npm-publish

name: publish npm to registry
on: push

jobs:
  eslint_check:
    name: Prepare action
    runs-on: ubuntu-latest
    steps:
      # Checkout action must run prior to eslint check
    - name: Checkout 
      uses: actions/checkout@v1
    - name: Lint
      uses: Krizzu/eslint-check-action@v1.1.0
      with:
        ghToken: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: eslint_check
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      # - run: npm test
      # 当提交消息包含publish major|minor就更新相应的版本，其他就更新patch
      - name: 基于提交信息自动更新版本号
        shell: bash
        run: |
          git config user.name ${{ github.event.head_commit.author.name }}
          git config user.email ${{ github.event.head_commit.author.email }}

          check_npmVersion_by_commit=".github/scripts/1.check_npmVersion_by_commit.sh"
          chmod +x $check_npmVersion_by_commit
          ./$check_npmVersion_by_commit "${{github.event.head_commit.message }}"

      - uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
