# referer: https://github.com/marketplace/actions/npm-publish

name: publish npm to registry
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      # - run: npm test
      - node_modules/.bin/eslint.cmd lib/index.js --fix
      - node_modules/.bin/eslint.cmd index.js --fix
      - run: npm version
      - uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true
          type: 'patch'
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"